; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.10-passed-arguments.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG3854	DB	'%d', 0aH, 00H
CONST	ENDS
PUBLIC	?function@@YAHHHH@Z				; function
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_c$ = 16						; size = 4
?function@@YAHHHH@Z PROC				; function
; File a:\re4b\chapter 1 - code patterns\1.10-passed-arguments.cpp
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _b$[ebp]
	add	eax, DWORD PTR _c$[ebp]
; Line 6
	pop	ebp
	ret	0
?function@@YAHHHH@Z ENDP				; function
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 8
	push	ebp
	mov	ebp, esp
; Line 9
	push	3
	push	2
	push	1
	call	?function@@YAHHHH@Z			; function
	add	esp, 12					; 0000000cH
	push	eax
	push	OFFSET $SG3854
	call	_printf
	add	esp, 8
; Line 10
	xor	eax, eax
; Line 11
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
