; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.11.3-return-struct.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG3865	DB	'%d - %d - %d', 0aH, 00H
CONST	ENDS
PUBLIC	?get_some_values@@YA?AUs@@H@Z			; get_some_values
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
$T3873 = 8						; size = 4
_a$ = 12						; size = 4
?get_some_values@@YA?AUs@@H@Z PROC			; get_some_values
; File a:\re4b\chapter 1 - code patterns\1.11.3-return-struct.cpp
; Line 12
	mov	ecx, DWORD PTR _a$[esp-4]
	mov	eax, DWORD PTR $T3873[esp-4]
	lea	edx, DWORD PTR [ecx+1]
	mov	DWORD PTR [eax], edx
; Line 13
	lea	edx, DWORD PTR [ecx+2]
; Line 14
	add	ecx, 3
	mov	DWORD PTR [eax+4], edx
	mov	DWORD PTR [eax+8], ecx
; Line 16
	ret	0
?get_some_values@@YA?AUs@@H@Z ENDP			; get_some_values
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 20
	push	7
	push	6
	push	5
	push	OFFSET $SG3865
	call	_printf
	add	esp, 16					; 00000010H
; Line 21
	xor	eax, eax
; Line 22
	ret	0
_main	ENDP
_TEXT	ENDS
END
