; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.12.2-return-multiple.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	_product:DWORD
COMM	_sum:DWORD
$SG2649	DB	'add=%d, product=%d', 0aH, 00H
_DATA	ENDS
PUBLIC	_f1
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_y$ = 12						; size = 4
_sum$ = 16						; size = 4
_product$ = 20						; size = 4
_f1	PROC
; File a:\re4b\chapter 1 - code patterns\1.12.2-return-multiple.c
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	mov	eax, DWORD PTR _x$[ebp]
	add	eax, DWORD PTR _y$[ebp]
	mov	ecx, DWORD PTR _sum$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 6
	mov	edx, DWORD PTR _x$[ebp]
	imul	edx, DWORD PTR _y$[ebp]
	mov	eax, DWORD PTR _product$[ebp]
	mov	DWORD PTR [eax], edx
; Line 7
	pop	ebp
	ret	0
_f1	ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 10
	push	ebp
	mov	ebp, esp
; Line 11
	push	OFFSET _product
	push	OFFSET _sum
	push	456					; 000001c8H
	push	123					; 0000007bH
	call	_f1
	add	esp, 16					; 00000010H
; Line 12
	mov	eax, DWORD PTR _product
	push	eax
	mov	ecx, DWORD PTR _sum
	push	ecx
	push	OFFSET $SG2649
	call	_printf
	add	esp, 12					; 0000000cH
; Line 13
	xor	eax, eax
; Line 14
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
