; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.12.1-swap-values.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2770	DB	'something', 00H
	ORG $+2
$SG2771	DB	'%s', 0aH, 00H
_DATA	ENDS
PUBLIC	_swap_bytes
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_first$ = 8						; size = 4
_second$ = 12						; size = 4
_swap_bytes PROC
; File a:\re4b\chapter 1 - code patterns\1.12.1-swap-values.c
; Line 9
	mov	eax, DWORD PTR _first$[esp-4]
	mov	cl, BYTE PTR [eax]
	push	esi
; Line 12
	mov	esi, DWORD PTR _second$[esp]
	mov	dl, BYTE PTR [esi]
	mov	BYTE PTR [eax], dl
; Line 13
	mov	BYTE PTR [esi], cl
	pop	esi
; Line 14
	ret	0
_swap_bytes ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	_strdup:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 17
	push	OFFSET $SG2770
	call	_strdup
; Line 19
	mov	dl, BYTE PTR [eax+3]
	mov	cl, BYTE PTR [eax+2]
; Line 20
	push	eax
	mov	BYTE PTR [eax+2], dl
	push	OFFSET $SG2771
	mov	BYTE PTR [eax+3], cl
	call	_printf
	add	esp, 12					; 0000000cH
; Line 21
	xor	eax, eax
; Line 22
	ret	0
_main	ENDP
_TEXT	ENDS
END
