; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.14.4-min-max.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2700	DB	'Min Max: ', 0aH, 00H
	ORG $+1
$SG2701	DB	'max_function(8,16) = %d', 0aH, 00H
	ORG $+3
$SG2702	DB	'min_function(16,8) = %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_max_function
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_max_function PROC
; File a:\re4b\chapter 1 - code patterns\1.14.4-min-max.c
; Line 6
	mov	eax, DWORD PTR _a$[esp-4]
	mov	ecx, DWORD PTR _b$[esp-4]
	cmp	eax, ecx
; Line 7
	jg	SHORT $LN1@max_functi
; Line 9
	mov	eax, ecx
$LN1@max_functi:
; Line 11
	ret	0
_max_function ENDP
_TEXT	ENDS
PUBLIC	_min_function
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_min_function PROC
; Line 14
	mov	eax, DWORD PTR _a$[esp-4]
	mov	ecx, DWORD PTR _b$[esp-4]
	cmp	eax, ecx
; Line 15
	jl	SHORT $LN1@min_functi
; Line 17
	mov	eax, ecx
$LN1@min_functi:
; Line 19
	ret	0
_min_function ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 23
	push	OFFSET $SG2700
	call	_printf
; Line 24
	push	16					; 00000010H
	push	OFFSET $SG2701
	call	_printf
; Line 25
	push	8
	push	OFFSET $SG2702
	call	_printf
	add	esp, 20					; 00000014H
; Line 27
	xor	eax, eax
; Line 28
	ret	0
_main	ENDP
_TEXT	ENDS
END
