; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.14.4-min-max-64.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2691	DB	'Min Max: ', 0aH, 00H
	ORG $+1
$SG2692	DB	'max_function(8,16) = %d', 0aH, 00H
	ORG $+3
$SG2693	DB	'min_function(16,8) = %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_max_function
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 8
_b$ = 16						; size = 8
_max_function PROC
; File a:\re4b\chapter 1 - code patterns\1.14.4-min-max-64.c
; Line 5
	push	ebp
	mov	ebp, esp
; Line 6
	mov	eax, DWORD PTR _a$[ebp+4]
	cmp	eax, DWORD PTR _b$[ebp+4]
	jl	SHORT $LN2@max_functi
	jg	SHORT $LN5@max_functi
	mov	ecx, DWORD PTR _a$[ebp]
	cmp	ecx, DWORD PTR _b$[ebp]
	jbe	SHORT $LN2@max_functi
$LN5@max_functi:
; Line 7
	mov	eax, DWORD PTR _a$[ebp]
	mov	edx, DWORD PTR _a$[ebp+4]
	jmp	SHORT $LN3@max_functi
; Line 8
	jmp	SHORT $LN3@max_functi
$LN2@max_functi:
; Line 9
	mov	eax, DWORD PTR _b$[ebp]
	mov	edx, DWORD PTR _b$[ebp+4]
$LN3@max_functi:
; Line 11
	pop	ebp
	ret	0
_max_function ENDP
_TEXT	ENDS
PUBLIC	_min_function
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 8
_b$ = 16						; size = 8
_min_function PROC
; Line 13
	push	ebp
	mov	ebp, esp
; Line 14
	mov	eax, DWORD PTR _a$[ebp+4]
	cmp	eax, DWORD PTR _b$[ebp+4]
	jg	SHORT $LN2@min_functi
	jl	SHORT $LN5@min_functi
	mov	ecx, DWORD PTR _a$[ebp]
	cmp	ecx, DWORD PTR _b$[ebp]
	jae	SHORT $LN2@min_functi
$LN5@min_functi:
; Line 15
	mov	eax, DWORD PTR _a$[ebp]
	mov	edx, DWORD PTR _a$[ebp+4]
	jmp	SHORT $LN3@min_functi
; Line 16
	jmp	SHORT $LN3@min_functi
$LN2@min_functi:
; Line 17
	mov	eax, DWORD PTR _b$[ebp]
	mov	edx, DWORD PTR _b$[ebp+4]
$LN3@min_functi:
; Line 19
	pop	ebp
	ret	0
_min_function ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 22
	push	ebp
	mov	ebp, esp
; Line 23
	push	OFFSET $SG2691
	call	_printf
	add	esp, 4
; Line 24
	push	0
	push	16					; 00000010H
	push	0
	push	8
	call	_max_function
	add	esp, 16					; 00000010H
	push	edx
	push	eax
	push	OFFSET $SG2692
	call	_printf
	add	esp, 12					; 0000000cH
; Line 25
	push	0
	push	16					; 00000010H
	push	0
	push	8
	call	_min_function
	add	esp, 16					; 00000010H
	push	edx
	push	eax
	push	OFFSET $SG2693
	call	_printf
	add	esp, 12					; 0000000cH
; Line 27
	xor	eax, eax
; Line 28
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
