; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.14.3-ternary-operator.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2686	DB	'It is ten', 00H
	ORG $+2
$SG2687	DB	'Not ten', 00H
$SG2690	DB	'Ternary Operator: ', 0aH, 00H
$SG2691	DB	'15 = %s', 0aH, 00H
	ORG $+3
$SG2692	DB	'10 = %s', 0aH, 00H
	ORG $+3
$SG2693	DB	'-5 = %s', 0aH, 00H
_DATA	ENDS
PUBLIC	_function
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a$ = 8							; size = 4
_function PROC
; File a:\re4b\chapter 1 - code patterns\1.14.3-ternary-operator.c
; Line 6
	cmp	DWORD PTR _a$[esp-4], 10		; 0000000aH
	mov	eax, OFFSET $SG2686
	je	SHORT $LN4@function
	mov	eax, OFFSET $SG2687
$LN4@function:
; Line 7
	ret	0
_function ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 10
	push	OFFSET $SG2690
	call	_printf
; Line 11
	push	OFFSET $SG2687
	push	OFFSET $SG2691
	call	_printf
; Line 12
	push	OFFSET $SG2686
	push	OFFSET $SG2692
	call	_printf
; Line 13
	push	OFFSET $SG2687
	push	OFFSET $SG2693
	call	_printf
	add	esp, 28					; 0000001cH
; Line 15
	xor	eax, eax
; Line 16
	ret	0
_main	ENDP
_TEXT	ENDS
END
