; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.14.2-abs.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2690	DB	'Absolute value for: ', 0aH, 00H
	ORG $+2
$SG2691	DB	'|-5| = %d', 0aH, 00H
	ORG $+1
$SG2692	DB	'|-8| = %d', 0aH, 00H
	ORG $+1
$SG2693	DB	'|15| = %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_my_abs
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_number$ = 8						; size = 4
_my_abs	PROC
; File a:\re4b\chapter 1 - code patterns\1.14.2-abs.c
; Line 5
	mov	eax, DWORD PTR _number$[esp-4]
	test	eax, eax
	jns	SHORT $LN1@my_abs
; Line 6
	neg	eax
$LN1@my_abs:
; Line 9
	ret	0
_my_abs	ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 12
	push	OFFSET $SG2690
	call	_printf
; Line 13
	push	5
	push	OFFSET $SG2691
	call	_printf
; Line 14
	push	8
	push	OFFSET $SG2692
	call	_printf
; Line 15
	push	15					; 0000000fH
	push	OFFSET $SG2693
	call	_printf
	add	esp, 28					; 0000001cH
; Line 17
	xor	eax, eax
; Line 18
	ret	0
_main	ENDP
_TEXT	ENDS
END
