; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.14.3-ternary-operator.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2639	DB	'It is ten', 00H
	ORG $+2
$SG2640	DB	'Not ten', 00H
$SG2643	DB	'Ternary Operator: ', 0aH, 00H
$SG2644	DB	'15 = %s', 0aH, 00H
	ORG $+3
$SG2645	DB	'10 = %s', 0aH, 00H
	ORG $+3
$SG2646	DB	'-5 = %s', 0aH, 00H
_DATA	ENDS
PUBLIC	_function
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv65 = -4						; size = 4
_a$ = 8							; size = 4
_function PROC
; File a:\re4b\chapter 1 - code patterns\1.14.3-ternary-operator.c
; Line 4
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 5
	cmp	DWORD PTR _a$[ebp], 10			; 0000000aH
	jne	SHORT $LN3@function
	mov	DWORD PTR tv65[ebp], OFFSET $SG2639
	jmp	SHORT $LN4@function
$LN3@function:
	mov	DWORD PTR tv65[ebp], OFFSET $SG2640
$LN4@function:
	mov	eax, DWORD PTR tv65[ebp]
; Line 6
	mov	esp, ebp
	pop	ebp
	ret	0
_function ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 8
	push	ebp
	mov	ebp, esp
; Line 9
	push	OFFSET $SG2643
	call	_printf
	add	esp, 4
; Line 10
	push	15					; 0000000fH
	call	_function
	add	esp, 4
	push	eax
	push	OFFSET $SG2644
	call	_printf
	add	esp, 8
; Line 11
	push	10					; 0000000aH
	call	_function
	add	esp, 4
	push	eax
	push	OFFSET $SG2645
	call	_printf
	add	esp, 8
; Line 12
	push	-5					; fffffffbH
	call	_function
	add	esp, 4
	push	eax
	push	OFFSET $SG2646
	call	_printf
	add	esp, 8
; Line 14
	xor	eax, eax
; Line 15
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
