; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.15.1-switch.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2644	DB	'Five', 0aH, 00H
	ORG $+2
$SG2646	DB	'Ten', 0aH, 00H
	ORG $+3
$SG2648	DB	'Fifteen', 0aH, 00H
	ORG $+3
$SG2650	DB	'Unknow Number', 0aH, 00H
_DATA	ENDS
PUBLIC	_switch_function
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv64 = -4						; size = 4
_value$ = 8						; size = 4
_switch_function PROC
; File a:\re4b\chapter 1 - code patterns\1.15.1-switch.c
; Line 4
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 5
	mov	eax, DWORD PTR _value$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 5
	je	SHORT $LN4@switch_fun
	cmp	DWORD PTR tv64[ebp], 10			; 0000000aH
	je	SHORT $LN3@switch_fun
	cmp	DWORD PTR tv64[ebp], 15			; 0000000fH
	je	SHORT $LN2@switch_fun
	jmp	SHORT $LN1@switch_fun
$LN4@switch_fun:
; Line 7
	push	OFFSET $SG2644
	call	_printf
	add	esp, 4
; Line 8
	jmp	SHORT $LN7@switch_fun
$LN3@switch_fun:
; Line 10
	push	OFFSET $SG2646
	call	_printf
	add	esp, 4
; Line 11
	jmp	SHORT $LN7@switch_fun
$LN2@switch_fun:
; Line 13
	push	OFFSET $SG2648
	call	_printf
	add	esp, 4
; Line 14
	jmp	SHORT $LN7@switch_fun
$LN1@switch_fun:
; Line 16
	push	OFFSET $SG2650
	call	_printf
	add	esp, 4
$LN7@switch_fun:
; Line 19
	mov	esp, ebp
	pop	ebp
	ret	0
_switch_function ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 21
	push	ebp
	mov	ebp, esp
; Line 22
	push	5
	call	_switch_function
	add	esp, 4
; Line 23
	push	11					; 0000000bH
	call	_switch_function
	add	esp, 4
; Line 24
	xor	eax, eax
; Line 25
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
