; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\sources\security\RE4B\Chapter 1 - Code Patterns\1.15.4-fall-though.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2695	DB	'is_whitespace(''a'') = %d', 0aH, 00H
	ORG $+3
$SG2696	DB	'is_whitespace('' '') = %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_is_whitespace
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_c$ = 8							; size = 1
_is_whitespace PROC
; File a:\sources\security\re4b\chapter 1 - code patterns\1.15.4-fall-though.c
; Line 7
	movsx	eax, BYTE PTR _c$[esp-4]
	add	eax, -9					; fffffff7H
	cmp	eax, 23					; 00000017H
	ja	SHORT $LN1@is_whitesp
	movzx	eax, BYTE PTR $LN7@is_whitesp[eax]
	jmp	DWORD PTR $LN8@is_whitesp[eax*4]
$LN2@is_whitesp:
; Line 9
	mov	eax, 1
; Line 13
	ret	0
$LN1@is_whitesp:
; Line 11
	xor	eax, eax
; Line 13
	ret	0
$LN8@is_whitesp:
	DD	$LN2@is_whitesp
	DD	$LN1@is_whitesp
$LN7@is_whitesp:
	DB	0
	DB	0
	DB	1
	DB	1
	DB	0
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	1
	DB	0
_is_whitespace ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 16
	push	0
	push	OFFSET $SG2695
	call	_printf
; Line 17
	push	1
	push	OFFSET $SG2696
	call	_printf
	add	esp, 16					; 00000010H
; Line 18
	xor	eax, eax
; Line 19
	ret	0
_main	ENDP
_TEXT	ENDS
END
