; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.15.1-switch.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2691	DB	'Five', 0aH, 00H
	ORG $+2
$SG2693	DB	'Ten', 0aH, 00H
	ORG $+3
$SG2695	DB	'Fifteen', 0aH, 00H
	ORG $+3
$SG2697	DB	'Unknow Number', 0aH, 00H
_DATA	ENDS
PUBLIC	_switch_function
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_value$ = 8						; size = 4
_switch_function PROC
; File a:\re4b\chapter 1 - code patterns\1.15.1-switch.c
; Line 6
	mov	eax, DWORD PTR _value$[esp-4]
	cmp	eax, 5
	je	SHORT $LN4@switch_fun
	cmp	eax, 10					; 0000000aH
	je	SHORT $LN3@switch_fun
	cmp	eax, 15					; 0000000fH
	je	SHORT $LN2@switch_fun
; Line 17
	mov	DWORD PTR _value$[esp-4], OFFSET $SG2697
	jmp	_printf
$LN2@switch_fun:
; Line 14
	mov	DWORD PTR _value$[esp-4], OFFSET $SG2695
	jmp	_printf
$LN3@switch_fun:
; Line 11
	mov	DWORD PTR _value$[esp-4], OFFSET $SG2693
	jmp	_printf
$LN4@switch_fun:
; Line 8
	mov	DWORD PTR _value$[esp-4], OFFSET $SG2691
	jmp	_printf
_switch_function ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 23
	push	OFFSET $SG2691
	call	_printf
; Line 24
	push	OFFSET $SG2697
	call	_printf
	add	esp, 8
; Line 25
	xor	eax, eax
; Line 26
	ret	0
_main	ENDP
_TEXT	ENDS
END
