; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.16.1-for.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2686	DB	'print_integer(%d)', 0aH, 00H
_DATA	ENDS
PUBLIC	_print_integer
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_i$ = 8							; size = 4
_print_integer PROC
; File a:\re4b\chapter 1 - code patterns\1.16.1-for.c
; Line 6
	mov	eax, DWORD PTR _i$[esp-4]
	push	eax
	push	OFFSET $SG2686
	call	_printf
	add	esp, 8
; Line 7
	ret	0
_print_integer ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 9
	push	esi
; Line 11
	mov	esi, 2
	npad	10
$LL3@main:
; Line 12
	push	esi
	push	OFFSET $SG2686
	call	_printf
	inc	esi
	add	esp, 8
	cmp	esi, 10					; 0000000aH
	jl	SHORT $LL3@main
; Line 14
	xor	eax, eax
	pop	esi
; Line 15
	ret	0
_main	ENDP
_TEXT	ENDS
END
