; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.16.1-for.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2639	DB	'print_integer(%d)', 0aH, 00H
_DATA	ENDS
PUBLIC	_print_integer
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = 8							; size = 4
_print_integer PROC
; File a:\re4b\chapter 1 - code patterns\1.16.1-for.c
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	mov	eax, DWORD PTR _i$[ebp]
	push	eax
	push	OFFSET $SG2639
	call	_printf
	add	esp, 8
; Line 6
	pop	ebp
	ret	0
_print_integer ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = -4						; size = 4
_main	PROC
; Line 8
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 10
	mov	DWORD PTR _i$[ebp], 2
	jmp	SHORT $LN3@main
$LN2@main:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN3@main:
	cmp	DWORD PTR _i$[ebp], 10			; 0000000aH
	jge	SHORT $LN1@main
; Line 11
	mov	ecx, DWORD PTR _i$[ebp]
	push	ecx
	call	_print_integer
	add	esp, 4
; Line 12
	jmp	SHORT $LN2@main
$LN1@main:
; Line 13
	xor	eax, eax
; Line 14
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
