; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\sources\security\RE4B\Chapter 1 - Code Patterns\1.18.1-multiplication-using-add.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2688	DB	'multiplication_function(15) = %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_multiplication_function
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_number$ = 8						; size = 4
_multiplication_function PROC
; File a:\sources\security\re4b\chapter 1 - code patterns\1.18.1-multiplication-using-add.c
; Line 5
	mov	eax, DWORD PTR _number$[esp-4]
	add	eax, eax
	add	eax, eax
	add	eax, eax
; Line 6
	ret	0
_multiplication_function ENDP
_TEXT	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 10
	push	120					; 00000078H
	push	OFFSET $SG2688
	call	_printf
	add	esp, 8
; Line 11
	xor	eax, eax
; Line 12
	ret	0
_main	ENDP
_TEXT	ENDS
END
