; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.19.7-float-comparison.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2644	DB	'd_max(1.2, 3.4) = %f', 0aH, 00H
	ORG $+2
$SG2645	DB	'd_max(1.212, 1.213) = %f', 0aH, 00H
_DATA	ENDS
PUBLIC	_d_max
EXTRN	__fltused:DWORD
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 8
_b$ = 16						; size = 8
_d_max	PROC
; File a:\re4b\chapter 1 - code patterns\1.19.7-float-comparison.c
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	fld	QWORD PTR _b$[ebp]
	fcomp	QWORD PTR _a$[ebp]
	fnstsw	ax
	test	ah, 5
	jp	SHORT $LN1@d_max
; Line 6
	fld	QWORD PTR _a$[ebp]
	jmp	SHORT $LN2@d_max
$LN1@d_max:
; Line 7
	fld	QWORD PTR _b$[ebp]
$LN2@d_max:
; Line 8
	pop	ebp
	ret	0
_d_max	ENDP
_TEXT	ENDS
PUBLIC	__real@3ff3645a1cac0831
PUBLIC	__real@3ff36872b020c49c
PUBLIC	__real@3ff3333333333333
PUBLIC	__real@400b333333333333
PUBLIC	_main
EXTRN	_printf:PROC
;	COMDAT __real@3ff3645a1cac0831
CONST	SEGMENT
__real@3ff3645a1cac0831 DQ 03ff3645a1cac0831r	; 1.212
CONST	ENDS
;	COMDAT __real@3ff36872b020c49c
CONST	SEGMENT
__real@3ff36872b020c49c DQ 03ff36872b020c49cr	; 1.213
CONST	ENDS
;	COMDAT __real@3ff3333333333333
CONST	SEGMENT
__real@3ff3333333333333 DQ 03ff3333333333333r	; 1.2
CONST	ENDS
;	COMDAT __real@400b333333333333
CONST	SEGMENT
__real@400b333333333333 DQ 0400b333333333333r	; 3.4
; Function compile flags: /Odtp
CONST	ENDS
_TEXT	SEGMENT
_main	PROC
; Line 10
	push	ebp
	mov	ebp, esp
; Line 11
	sub	esp, 8
	fld	QWORD PTR __real@400b333333333333
	fstp	QWORD PTR [esp]
	sub	esp, 8
	fld	QWORD PTR __real@3ff3333333333333
	fstp	QWORD PTR [esp]
	call	_d_max
	add	esp, 8
	fstp	QWORD PTR [esp]
	push	OFFSET $SG2644
	call	_printf
; Line 12
	add	esp, 4
	fld	QWORD PTR __real@3ff36872b020c49c
	fstp	QWORD PTR [esp]
	sub	esp, 8
	fld	QWORD PTR __real@3ff3645a1cac0831
	fstp	QWORD PTR [esp]
	call	_d_max
	add	esp, 8
	fstp	QWORD PTR [esp]
	push	OFFSET $SG2645
	call	_printf
	add	esp, 12					; 0000000cH
; Line 13
	xor	eax, eax
; Line 14
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
