; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.19.6-passing-float.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2856	DB	'32.01 ** 1.54 = %lf', 0aH, 00H
_DATA	ENDS
PUBLIC	__real@3ff8a3d70a3d70a4
PUBLIC	__real@40400ccccccccccd
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	__fltused:DWORD
EXTRN	__CIpow:PROC
;	COMDAT __real@3ff8a3d70a3d70a4
; File a:\sources\security\re4b\chapter 1 - code patterns\1.19.6-passing-float.c
CONST	SEGMENT
__real@3ff8a3d70a3d70a4 DQ 03ff8a3d70a3d70a4r	; 1.54
CONST	ENDS
;	COMDAT __real@40400ccccccccccd
CONST	SEGMENT
__real@40400ccccccccccd DQ 040400ccccccccccdr	; 32.1
; Function compile flags: /Ogtpy
CONST	ENDS
_TEXT	SEGMENT
_main	PROC
; Line 6
	fld	QWORD PTR __real@40400ccccccccccd
	fld	QWORD PTR __real@3ff8a3d70a3d70a4
	call	__CIpow
	sub	esp, 8
	fstp	QWORD PTR [esp]
	push	OFFSET $SG2856
	call	_printf
	add	esp, 12					; 0000000cH
; Line 7
	xor	eax, eax
; Line 8
	ret	0
_main	ENDP
_TEXT	ENDS
END
