; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.20.2-bo.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2642	DB	'a[20] = %d', 0aH, 00H
_DATA	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = -92						; size = 4
_a$ = -88						; size = 80
__$ArrayPad$ = -4					; size = 4
_main	PROC
; File a:\re4b\chapter 1 - code patterns\1.20.2-bo.c
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 92					; 0000005cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 7
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN3@main
$LN2@main:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN3@main:
	cmp	DWORD PTR _i$[ebp], 20			; 00000014H
	jge	SHORT $LN1@main
; Line 8
	mov	ecx, DWORD PTR _i$[ebp]
	shl	ecx, 1
	mov	edx, DWORD PTR _i$[ebp]
	mov	DWORD PTR _a$[ebp+edx*4], ecx
; Line 9
	jmp	SHORT $LN2@main
$LN1@main:
; Line 11
	mov	eax, DWORD PTR _a$[ebp+80]
	push	eax
	push	OFFSET $SG2642
	call	_printf
	add	esp, 8
; Line 13
	xor	eax, eax
; Line 14
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
