; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.3-empty-function.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File a:\re4b\chapter 1 - code patterns\1.3-empty-function.cpp
; Line 4
	xor	eax, eax
; Line 5
	ret	0
_main	ENDP
_TEXT	ENDS
END
