; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.4-returning-value.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File a:\re4b\chapter 1 - code patterns\1.4-returning-value.cpp
; Line 3
	mov	eax, 123				; 0000007bH
; Line 4
	ret	0
_main	ENDP
_TEXT	ENDS
END
