; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.7.4-noise-in-stack-fixed.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG3857	DB	'%d, %d, %d', 0aH, 00H
CONST	ENDS
PUBLIC	?f1@@YAXAAH00@Z					; f1
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_c$ = 16						; size = 4
?f1@@YAXAAH00@Z PROC					; f1
; File a:\re4b\chapter 1 - code patterns\1.7.4-noise-in-stack-fixed.cpp
; Line 3
	push	ebp
	mov	ebp, esp
; Line 4
	mov	eax, DWORD PTR _a$[ebp]
	mov	DWORD PTR [eax], 1
; Line 5
	mov	ecx, DWORD PTR _b$[ebp]
	mov	DWORD PTR [ecx], 2
; Line 6
	mov	edx, DWORD PTR _c$[ebp]
	mov	DWORD PTR [edx], 3
; Line 7
	pop	ebp
	ret	0
?f1@@YAXAAH00@Z ENDP					; f1
_TEXT	ENDS
PUBLIC	?f2@@YAXHHH@Z					; f2
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_c$ = 16						; size = 4
?f2@@YAXHHH@Z PROC					; f2
; Line 9
	push	ebp
	mov	ebp, esp
; Line 10
	mov	eax, DWORD PTR _c$[ebp]
	push	eax
	mov	ecx, DWORD PTR _b$[ebp]
	push	ecx
	mov	edx, DWORD PTR _a$[ebp]
	push	edx
	push	OFFSET $SG3857
	call	_printf
	add	esp, 16					; 00000010H
; Line 11
	pop	ebp
	ret	0
?f2@@YAXHHH@Z ENDP					; f2
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_c$ = -12						; size = 4
_b$ = -8						; size = 4
_a$ = -4						; size = 4
_main	PROC
; Line 13
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 16
	lea	eax, DWORD PTR _c$[ebp]
	push	eax
	lea	ecx, DWORD PTR _b$[ebp]
	push	ecx
	lea	edx, DWORD PTR _a$[ebp]
	push	edx
	call	?f1@@YAXAAH00@Z				; f1
	add	esp, 12					; 0000000cH
; Line 17
	mov	eax, DWORD PTR _c$[ebp]
	push	eax
	mov	ecx, DWORD PTR _b$[ebp]
	push	ecx
	mov	edx, DWORD PTR _a$[ebp]
	push	edx
	call	?f2@@YAXHHH@Z				; f2
	add	esp, 12					; 0000000cH
; Line 18
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
