; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.8-printf-several-args.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG3849	DB	'a=%d; b=%d; c=%d', 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File a:\re4b\chapter 1 - code patterns\1.8-printf-several-args.cpp
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	push	3
	push	2
	push	1
	push	OFFSET $SG3849
	call	_printf
	add	esp, 16					; 00000010H
; Line 6
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
