; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.9.4-scanf-validation.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG3850	DB	'Enter x:', 0aH, 00H
	ORG $+2
$SG3852	DB	'%d', 00H
	ORG $+1
$SG3853	DB	'Your entered value = %d', 0aH, 00H
	ORG $+3
$SG3855	DB	'Just numbers, please!', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_scanf:PROC
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = -4						; size = 4
_main	PROC
; File a:\re4b\chapter 1 - code patterns\1.9.4-scanf-validation.cpp
; Line 4
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 6
	push	OFFSET $SG3850
	call	_printf
	add	esp, 4
; Line 7
	lea	eax, DWORD PTR _x$[ebp]
	push	eax
	push	OFFSET $SG3852
	call	_scanf
	add	esp, 8
	cmp	eax, 1
	jne	SHORT $LN2@main
; Line 8
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	push	OFFSET $SG3853
	call	_printf
	add	esp, 8
; Line 9
	jmp	SHORT $LN1@main
$LN2@main:
; Line 10
	push	OFFSET $SG3855
	call	_printf
	add	esp, 4
$LN1@main:
; Line 13
	xor	eax, eax
; Line 14
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
