; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	A:\RE4B\Chapter 1 - Code Patterns\1.9.3-global-variables.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?x@@3HA						; x
_BSS	SEGMENT
?x@@3HA	DD	01H DUP (?)				; x
_BSS	ENDS
CONST	SEGMENT
$SG3850	DB	'Enter x:', 0aH, 00H
	ORG $+2
$SG3851	DB	'%d', 00H
	ORG $+1
$SG3852	DB	'Your entered value = %d', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_scanf:PROC
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File a:\re4b\chapter 1 - code patterns\1.9.3-global-variables.cpp
; Line 6
	push	ebp
	mov	ebp, esp
; Line 7
	push	OFFSET $SG3850
	call	_printf
	add	esp, 4
; Line 8
	push	OFFSET ?x@@3HA				; x
	push	OFFSET $SG3851
	call	_scanf
	add	esp, 8
; Line 10
	mov	eax, DWORD PTR ?x@@3HA			; x
	push	eax
	push	OFFSET $SG3852
	call	_printf
	add	esp, 8
; Line 11
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
